# Generated by Django 4.1.4 on 2022-12-19 18:28

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=22,
                        max_length=22,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField(max_length=50)),
                ("completed", models.BooleanField()),
                ("date", models.DateField()),
            ],
        ),
    ]
